#+title: Saunf

Saunf is a software project management tool, which allows doing collaborative
project management in plain text.

Not everyone is a plain-text fan, so to keep the spirit of collaboration alive,
saunf has keeping different tools in sync as its core idea. You can create your
entire project as a single org file, and saunf will take care of keeping things
in sync with e.g github-issues for creating issues for user stories and readme.md
to maintain a good front-facing documentation.

* Features

** Documentation management

Define the structure of your readme file, and keep it in sync with your main
project file.

** User Story management

Define user stories in your project file, and keep them in sync with github
issues.

* Stories

** Create a CLI which can read saunf.dhall configuration

** Generate readme.md file from main doc file as defined in saunf.dhall
- Fall back to =docs/readme.org= for main doc file if ~saunf.dhall~ is missing


* Configuration

** Readme
:PROPERTIES:
:ID:       79e80db6-a1bd-4476-b6e6-3644c07ade27
:END:

#+begin_src markdown
  # $$title$$

  $$description$$

  ## $#features$
#+end_src
